version: '3.8'

services:
  db:
    container_name: "db_prod"
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dinht
      - POSTGRES_DB=music
      - POSTGRES_PASSWORD=Dinhthehuy0811
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  web:
    container_name: "web_prod"
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - .:/code
      - static_volume:/code/staticfiles
    expose:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    container_name: "nginx_prod"
    build: ./nginx
    volumes:
      - static_volume:/code/staticfiles
    ports:
      - "1337:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: