version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dinht
      - POSTGRES_DB=music
      - POSTGRES_PASSWORD=Dinhthehuy0811

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./logNewAlbum/.env
    depends_on:
      - db

volumes:
  postgres_data: