version: '3.8'

services:
  db:
    container_name: "db_dev"
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dinht
      - POSTGRES_DB=music_dev
      - POSTGRES_PASSWORD=Dinhthehuy0811
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  web:
    container_name: "web_dev"
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    env_file:
      - .env.dev
    depends_on:
      - db

volumes:
  postgres_data: